chart:
  # when helm is a tgz
  # url: https://github.com/krateoplatformops/krateo-v2-template-fireworksapp/releases/download/0.1.0/fireworks-app-0.1.0.tgz

  # when helm is a OCI image
  # url: oci://registry-1.docker.io/bitnamicharts/postgresql
  # version: "12.8.3"

  # when helm is in a registry
  url: https://charts.krateo.io
  version: 1.0.19
  repo: fireworks-app


  # insecureSkipVerifyTLS: true

  # credentials:
  #   username: username
  #   passwordRef: # reference to a secret
  #     key: token
  #     name: helm-registry-token
  #     namespace: krateo-system

card:
  icon: fa-cubes
  title: FireworksApp
  color: blue
  content: This is a card for FireworksApp template
